### ISSUE TITLE
默认开启，怎么设置

### ISSUE THREAD

**Issue by liguangze** [Hitomis/SpinMenu#5]

**Comment by liguangze** [comment]
向下一拉才能轮播，这样然让第一次使用的人不知道怎么操作，建议第一次进来就是开启状态，怎么设置

**Comment by Hitomis** [comment]
SpinMenu.openMenu().
你可以把代码导入项目，然后拿到spinMenu.  点一下，as自动提示功能足以看到这几个简单的api。
不过还是不建议这么做，进来就自动打开，页面内容变化区域太夸张，不友好。
如果给一个 GuideView 做动画提示，这样用户体验岂不是更好

**Comment by liguangze** [comment]
SpinMenu.openMenu().这个方法报错呢，我导入了

**Comment by Hitomis** [comment]
以后提问题，请附带上报错信息。以及一些相关代码信息，否则你就说个报错，我怎么知道报什么错呢？

**Comment by liguangze** [comment]
知道了，，

   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hitomi.smlibrary.SpinMenuAnimator.openMenuAnimator()' on a null object reference
                                                                at com.hitomi.smlibrary.SpinMenu.openMenu(SpinMenu.java:356)
                                                                at com.lotter.util.NewMainActivity.onCreate(NewMainActivity.java:43)
                                                                at android.app.Activity.performCreate(Activity.java:6847)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 

我感觉设置   spinMenu.updateMenuState(1);spinMenu.updateMenuState(2);也不起作用呢
